font_family JetBrains Mono
font_size 11.0
foreground #efefeb
background #1c1c1c
background_opacity 0.92
selection_foreground #1c1c1c
selection_background #efefeb
cursor #efefeb
cursor_text_color #1c1c1c
active_border_color #efefeb
inactive_border_color #525252
window_padding_width 16
enable_audio_bell no
allow_remote_control no